### ISSUE TITLE
[Question] Animation while sliding the keyboard out

### ISSUE THREAD

**Issue by furkansarihan** [drogel/keyboard_attachable#13]
I have a common messaging screen layout.

This package works expected. (Thanks!)

And I tried to enhance the behaviour with [flutter_interactive_keyboard](https://pub.dev/packages/flutter_interactive_keyboard)

![ezgif com-resize](https://user-images.githubusercontent.com/27918319/89942325-0a202180-dc25-11ea-9515-fe491d91f094.gif)

The result is not bad. But obviously what I need here is snapping the footer widget to the bottom while keyboard position updates rather than animated between two values when focus changed.

Is there any idea?

**Comment by drogel** [comment]
Hi furkansarihan,

Thanks a lot for using the package! I am very happy to see that it inspired others to build more complex behaviour, very nice work! 

Regarding the footer snapping animation, I have not had the time to take a deep dive into your package's code, but one idea comes to mind. I would suggest you to check the `transition_builder` example from the example folder in the `keyboard_attachable` package. That example uses a `transitionBuilder` parameter to animate a button and a text field in sync with the keyboard hiding and showing.

What I did to achieve that behaviour was to include a callback function to the `KeyboardAttachable` builder, in which I passed the `animation` for the keyboard, so that consumers could access the animation and use it to run whatever animation they needed to sync with the keyboard. 

If you take a look at the `src` from `keyboard_attachable`, you will find the implementation details in `keyboard_attachable.dart`. Basically I declared the callback like this:

```dart
/// Signature for builders used in custom transitions for KeyboardAttachable.
///
/// The function should return a widget which wraps the given [child].
/// It may also use the animation to inform its transition.
typedef KeyboardTransitionBuilder = Widget Function(
  Widget child,
  Animation<double> animation,
  double keyboardHeight,
);
```

and then I called the callback in the `build` method of `KeyboardAttachable` like this, passing the `animation` that `KeyboardAttachable` uses:

```dart
@override
  Widget build(BuildContext context) {
    // ...
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        if (child != null)
          widget.transitionBuilder(child, animation, _bottomInset),
        SizeTransition(...),
        ),
      ],
    );
  }
```

And that is how I would do it. I am not sure if this `animation` callback approach suits your implementation case, but I hope it points you towards the right direction. Anyways, if you have any further questions, don't hesitate to ask me!

**Comment by furkansarihan** [comment]
Unfortunate, I am not the author of the [flutter_interactive_keyboard](https://pub.dev/packages/flutter_interactive_keyboard) 

I will look into `transition_builder`.  Thanks for the explanation!

**Comment by drogel** [comment]
Oh, my bad! I thought you were a contributor to that project. I guess you can still propose a new feature for it. Either way, you will need some way to access the animation controller value that is driving the keyboard animation, and the way that is usually done in Flutter is through an animation callback like the one I showed to you. You can find several more examples of such an approach in the framework itself. For example, if I remember correctly, `AnimatedSwitcher` has a very similar callback to let the consumer control what happens during the animation.

Good luck, and glad to help!
