### ISSUE TITLE
The child element is not rendered

### ISSUE THREAD

**Issue by renrique92** [drogel/keyboard_attachable#14]
My code:

`
Scaffold(
          resizeToAvoidBottomInset: false,
          body: FooterLayout(
            footer: Container(
              child: InputField(controller: null, placeholder: 'Type Here'),
            ),
            child: Text('PRUEBA'),
          ),
        ),
      );
`

The result:

![image](https://user-images.githubusercontent.com/12242257/91796766-60b2c700-ebf7-11ea-9549-d6e62bffb648.png)

The text widget with PRUEBA is not shown

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.1016], locale es-AR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.48.2)
[√] Connected device (2 available)

• No issues found!

**Comment by drogel** [comment]
Hi! Thanks for using the package and for raising this issue.

From the information you provide, my first guess it's that the `InputField` you are using is somehow pushing/expanding to fill all the space available to it, leaving no room for the `child` to be rendered. This is because of the way `FooterLayout` is built. From the `FooterLayout` class documentation:

```dart
/// A widget that can lay out a child widget above a footer.
///
/// This widget builds a [CustomMultiChildLayout] whose delegate loosely
/// positions a footer widget at the bottom of the available space first,
/// and then positions a child widget in the remaining space with loose
/// constraints.
class FooterLayout extends StatelessWidget {
  ...
}
```

As you can see, `FooterLayout` renders the footer *first* and then places the child in the remaining space. This means that if the footer is trying to take all the available space, the child might not have any room available.

I would suggest you to check if this might be the case in your code, maybe replacing your `InputField` with a standard `TextField`, which has a fixed height, just to be sure that the footer is not trying to take all the space available to it.

If the problem still persists, please provide a minimal reproducible example of the bug so I can take a deeper look at it. Thanks!
