### ISSUE TITLE
if there is multiple textfield in same page, the attachable toolbar will response to all textfield focus/unfocuse events..

### ISSUE THREAD

**Issue by hurricane009** [drogel/keyboard_attachable#24]
because the KeyboardVisibilityController is binding to global keyboard, instead of binding to a specified TextFiled instance.

**Comment by drogel** [comment]
Hi @hurricane009,

Thanks for using the package and for raising this issue. As you mentioned, the part of the logic that is responsible of reacting to keyboard events is bound to the global keyboard, and not to a specific `TextField` instance. That is the intended behavior. I am guessing that you need the `KeyboardAttachable` to react only to certain `TextField` instances instead of reacting everytime the keyboard is shown, right? 

In order to develop such a feature, it would be very helpful for me to have a code sample of your current layout, the one in which you try to achieve this behavior. This way it will be easier for me to figure out exactly what you want.

Thanks!
